name: lint and build docker image

on:
  pull_request:

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v2
      - name: lint base
        uses: luke142367/Docker-Lint-Action@v1.1.1
        with:
          target: 0-base/deployments/Dockerfile
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - name: lint measured
        uses: luke142367/Docker-Lint-Action@v1.1.1
        with:
          target: 0-measured/deployments/Dockerfile
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - name: lint optimized
        uses: luke142367/Docker-Lint-Action@v1.1.1
        with:
          target: 0-optimized/deployments/Dockerfile
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - name: lint recommended
        uses: luke142367/Docker-Lint-Action@v1.1.1
        with:
          target: 0-recommended/deployments/Dockerfile
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
  build-base-image:
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v2
      - name: setup qemu
        uses: docker/setup-qemu-action@v1
      - name: setup docker buildx
        uses: docker/setup-buildx-action@v1
      - name: build base
        uses: docker/build-push-action@v2
        with:
          tags: kamsz/tilt-example-go:base-${{ github.sha }}
          context: "{{defaultContext}}:0-base"
          file: "{{defaultContext}}:0-base/deployment/Dockerfile"
          push: false
          cache-from: type=gha
          cache-to: type=gha,mode=max
  build-measured-image:
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v2
      - name: setup qemu
        uses: docker/setup-qemu-action@v1
      - name: setup docker buildx
        uses: docker/setup-buildx-action@v1
      - name: build measured
        uses: docker/build-push-action@v2
        with:
          tags: kamsz/tilt-example-go:measured-${{ github.sha }}
          context: "{{defaultContext}}:1-measured"
          file: "{{defaultContext}}:1-measured/deployment/Dockerfile"
          push: false
          cache-from: type=gha
          cache-to: type=gha,mode=max
  build-optimized-image:
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v2
      - name: setup qemu
        uses: docker/setup-qemu-action@v1
      - name: setup docker buildx
        uses: docker/setup-buildx-action@v1
      - name: build optimized
        uses: docker/build-push-action@v2
        with:
          tags: kamsz/tilt-example-go:optimized-${{ github.sha }}
          context: "{{defaultContext}}:2-optimized"
          file: "{{defaultContext}}:2-optimized/deployment/Dockerfile"
          push: false
          cache-from: type=gha
          cache-to: type=gha,mode=max
  build-recommended-image:
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v2
      - name: setup qemu
        uses: docker/setup-qemu-action@v1
      - name: setup docker buildx
        uses: docker/setup-buildx-action@v1
      - name: build recommended
        uses: docker/build-push-action@v2
        with:
          tags: kamsz/tilt-example-go:recommended-${{ github.sha }}
          context: "{{defaultContext}}:3-recommended"
          file: "{{defaultContext}}:3-recommended/deployment/Dockerfile"
          push: false
          cache-from: type=gha
          cache-to: type=gha,mode=max
